### ISSUE TITLE
Invalid number error

### ISSUE THREAD

**Issue by brunojppb** [suchitpuri/emberjs-essentials#1]
@suchitpuri

I have got an Invalid Number error when I tried to follow the observer sample.(emberjs-essentials/chapter-2/example8/app/time_manager.js)

``` javascript
export default Ember.Object.extend({
  time: 00,
  timeChanged: function(){
    console.log('Time changed');
  }.observes('time')
});
```

I changed to:

``` javascript
export default Ember.Object.extend({
  time: 0,
  timeChanged: function(){
    console.log('Time changed');
  }.observes('time')
});
```

and works.

**Comment by suchitpuri** [comment]
Thanks for raising the issue @brunojppb , looks like a valid one, fixing it

**Comment by brunojppb** [comment]
I just bought your book yesterday and it is amazing!

**Comment by suchitpuri** [comment]
Thanks @brunojppb , it would be great if you could write a review at amazon.
http://www.amazon.com/Ember-js-Web-Development-Ember-CLI-ebook/dp/B00YEVZ6WI/ref=sr_1_1?ie=UTF8&qid=1432921546&sr=8-1&keywords=suchit+puri

**Comment by brunojppb** [comment]
Sure @suchitpuri. I am at 50% of the book. As soon as I get it done I will leave a review. It is pretty good so far.
