### ISSUE TITLE
$.number is not a function

### ISSUE THREAD

**Issue by brunojppb** [suchitpuri/emberjs-essentials#4]
It seems you are using the jQuery number plugin but you did not include this step.

``` javascript
return this.get('symbol') + ' ' + $.number(this.get('price'), 2);
```

How can I add this plugin to my ember app?

Path:

``` console
emberjs-essentials/chapter-5/example1/app/controllers/product.js
```

**Comment by suchitpuri** [comment]
Hi @brunojppb please have a look at https://github.com/suchitpuri/emberjs-essentials/blob/master/chapter-5/example1/Brocfile.js , it imports the jquery number. Try running bower install it should work fine.
