### ISSUE TITLE
Chapter 5 example is different than mentioned in the book

### ISSUE THREAD

**Issue by zalun** [suchitpuri/emberjs-essentials#9]
cite: "Product controller is present at app/controllers/products/product.js"

  ls -l chapter-5/example1/app/controllers/
  -rw-r--r--  1 pzalewa  staff  168 14 Sep 12:37 application.js
  drwxr-xr-x  3 pzalewa  staff  102 14 Sep 12:37 product
  -rw-r--r--  1 pzalewa  staff  624 14 Sep 12:37 product.js
  -rw-r--r--  1 pzalewa  staff  162 14 Sep 12:37 products.js

**Comment by suchitpuri** [comment]
Thanks will correct it .
